version: '3.1'

volumes:
  postgres:

services:
  app:
    image: '96e30599638ca779e8bbca3c360f044b90f3ed7020a04a9d5d916a5720b79fa8'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      DB_USER: wallet
      DB_PASSWORD: 12345
      DB_URL: jdbc:postgresql://db:5432/wallet
    depends_on:
      - db
  db:
    image: "postgres"
    container_name: db
    ports:
      - "5435:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "wallet"
      POSTGRES_PASSWORD: "12345"
      PGDATA: "/data/postgres"
      POSTGRES_DB: "wallet"

